package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NbaFactModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String flightNo;

	public NbaFactModel() {
	}

	public java.lang.String getFlightNo() {
		return this.flightNo;
	}

	public void setFlightNo(java.lang.String flightNo) {
		this.flightNo = flightNo;
	}

	public NbaFactModel(java.lang.String flightNo) {
		this.flightNo = flightNo;
	}

}