package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FactModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String flightno;

	public FactModel() {
	}

	public java.lang.String getFlightno() {
		return this.flightno;
	}

	public void setFlightno(java.lang.String flightno) {
		this.flightno = flightno;
	}

	public FactModel(java.lang.String flightno) {
		this.flightno = flightno;
	}

}